services:
  web:
    image: nginx:1.27-alpine
    ports:
      - "3000:80"
    volumes:
      - ./code:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:8.2-fpm
    container_name: lab2_php
    volumes:
      - ./code:/var/www/html
    expose:
      - "9000"

